version: '3.9'
services:
  matching:
    build: ./app/
    volumes:
      - ./app/data/:/app/data/
      - ./app/model/:/app/model/
      - ./app/logs/:/app/logs/
    ports:
      - 5001:5000
    environment:
      -PORT: 5000