name: Docker Series Builds

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Check Out Repo 
      uses: actions/checkout@v2
    - name: Login to Docker Hub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKER_HUB_USERNAME }}
        password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
    - name: docker_build
      run: |
        docker build ./app -t sys_recommender:1.0.0
    - name: docker push
      run: |
        docker push ${{ secrets.DOCKER_HUB_USERNAME }}/sys_recommender:1.0.0

    - name: Image digest
      run: echo ${{ steps.docker_build.outputs.digest }}
